<?php
require_once __DIR__ . '/config.php';
require_once __DIR__ . '/api/bootstrap.php';
?><!doctype html>
<html lang="pt-BR">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Rádio Social Plus Brasil — Ao vivo</title>
  <meta name="description" content="Ouça a Rádio Social Plus Brasil ao vivo, vote nas músicas e acompanhe as mais votadas.">
  <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Outfit:wght@400;500;600;700;800&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="assets/style.css?v=top10-covers1">
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-97DXJD08VP"></script>
  <script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config','G-97DXJD08VP');</script>
  <script>window.OneSignal=window.OneSignal||[];window.OneSignal.push(function(){if(!window._oneSignalInitOptions||!window.OneSignal.init)return;window.OneSignal.SERVICE_WORKER_UPDATER_PATH="wp-content/plugins/onesignal-free-web-push-notifications/sdk_files/OneSignalSDKWorker.js";window.OneSignal.SERVICE_WORKER_PATH="wp-content/plugins/onesignal-free-web-push-notifications/sdk_files/OneSignalSDKWorker.js";window.OneSignal.SERVICE_WORKER_PARAM={scope:"wp-content/plugins/onesignal-free-web-push-notifications/sdk_files/"};delete window._oneSignalInitOptions.path;window.OneSignal.init(window._oneSignalInitOptions)});</script>
</head>
<body>
  <div class="grain"></div>
  <header class="topbar"><a class="brand" href="/"><img src="assets/logo.png" alt="Rádio Social Plus Brasil"></a><div class="top-actions"><span class="live-pill"><i></i><span>NO AR AGORA</span><b id="menuTrack">Rádio Social Plus Brasil</b></span><div id="authArea"><button class="text-btn" id="loginOpen">Faça seu login <span>↗</span></button><a class="outline-btn" href="register.php" target="_blank">Cadastre-se</a></div></div></header>
  <main>
    <section class="hero container">
      <div class="hero-copy"><p class="eyebrow">A rádio que conecta você</p><h1>Sinta, ouça<br>e <em>compartilhe</em></h1><p class="hero-sub">Música, informação e conexão em um só lugar. Dê o play e fique com a gente.</p><div class="hero-meta"><span>◉  AO VIVO 24H</span><span>✦  BRASIL</span></div><section class="vote-section vote-hero"><div class="section-head"><div><p class="eyebrow">A comunidade decide</p><h2>O que você achou<br>dessa música?</h2></div><div class="vote-count"><strong id="voteCount">0</strong><span>votos na faixa atual</span></div></div><div class="vote-actions"><button class="vote-btn like" data-vote="like"><span>♡</span><div><b>Gostei!</b><small>Quero ouvir de novo</small></div></button><button class="vote-btn dislike" data-vote="dislike"><span>♧</span><div><b>Não curti</b><small>Ajude a gente a escolher</small></div></button></div></section></div>
      <div class="now-card"><div class="now-label"><span class="equalizer"><b></b><b></b><b></b><b></b></span> TOCANDO AGORA</div><div class="art-wrap"><img id="albumArt" src="assets/logo.png" alt="Capa do álbum"><div class="art-glow"></div><div class="vu-meter" id="vuMeter" aria-label="V.U. visualizador de áudio"><?php for($i=0;$i<18;$i++): ?><i></i><?php endfor; ?></div></div><div class="track-info"><div><h2 id="trackTitle">Rádio Social Plus Brasil</h2><p id="trackArtist">A sua rádio, a qualquer hora</p></div><span class="signal">●</span></div><div class="player"><button class="play-btn" id="playBtn" aria-label="Tocar rádio">▶</button><div class="player-details"><div class="progress"><span></span></div><div class="player-times"><small id="playerStatus">Pronto para ouvir</small><small>AO VIVO</small></div></div><label class="volume">◖<input id="volume" type="range" min="0" max="1" step=".01" value=".8"></label></div><audio id="radio" preload="none" crossorigin="anonymous" src="<?php echo htmlspecialchars(RADIO_STREAM); ?>"></audio></div>
    </section>
    <section class="content-grid container"><div class="main-col"><section class="top-section"><div class="section-title-row"><div><p class="eyebrow">A preferência de quem ouve</p><h2>AS TOP 10 <em>MAIS VOTADAS</em></h2></div><span class="period">ESTA SEMANA　⌄</span></div><div id="topList" class="top-list"></div></section></div><aside class="side-col"><section class="activity"><div class="side-title"><span class="live-dot"></span><div><p class="eyebrow">Em tempo real</p><h3>QUEM ESTÁ VOTANDO</h3></div></div><div id="activityList"></div><div class="activity-note">Os votos da comunidade aparecem aqui na hora.</div></section><section class="community-card"><span>✦</span><h3>Faça parte<br>da nossa comunidade</h3><p>Cadastre-se para votar, acompanhar seu histórico e ajudar a escolher a programação.</p><a href="register.php" target="_blank">Criar minha conta　→</a></section></aside></section>
  </main>
  <section class="content-ad container" aria-label="Publicidade"><script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2249929574270161" crossorigin="anonymous"></script><ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-2249929574270161" data-ad-slot="8089461705" data-ad-format="auto" data-full-width-responsive="true"></ins><script>(adsbygoogle=window.adsbygoogle||[]).push({});</script></section>
  <footer><div class="footer-top container"><div class="footer-heading"><img src="assets/logo.png" alt="Rádio Social Plus Brasil"><p class="eyebrow">No site da rádio</p><h3>Conteúdos recentes</h3></div><div id="posts" class="posts"></div></div><div class="footer-bottom container"><span>© <?php echo date('Y'); ?> Rádio Social Plus Brasil</span><span>Feito para quem vive de música.</span></div></footer>
  <div class="modal-backdrop" id="loginModal"><div class="login-modal"><button class="close" id="loginClose">×</button><p class="eyebrow">Bem-vindo de volta</p><h2>Entrar na rádio</h2><form id="loginForm"><label>Login ou e-mail<input name="login" required autocomplete="username"></label><label>Senha<input name="password" type="password" required autocomplete="current-password"></label><button class="primary-btn">Entrar　→</button><p id="loginMessage" class="form-message"></p></form><p class="modal-foot">Ainda não tem cadastro? <a href="register.php" target="_blank">Crie sua conta</a></p></div></div>
  <script>window.RADIO_CONFIG=<?php echo json_encode(['apiBase'=>'api','lastfmKey'=>LASTFM_API_KEY,'stream'=>RADIO_STREAM]); ?>;</script><script src="assets/app.js?v=top10-covers1"></script>
</body></html>
